### ISSUE TITLE
Post-process videos

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2019#128]
A tracking issue for the work of processing the videos. Pulling on previous notes from [August](https://github.com/ournetworks/2019/blob/master/notes/2019-08-26-a-v-call.md):
- Produced video time estimation for post-processing
    - Two streams of video + 1 stream of audio
    - Estimate 2 hours per talk but depends on talk length
    - Need to watch them at least once
    - 22 talks, 15.5 hours of recordings
        - 2 orga 
        - 2 lightning 
        - 18 presenters
    - ~30 min overhead to set up each video:
        - Lower thirds
        - Metadata
        - Project setup (using templates this year)
    - Post-processing & publishing plan
        - `0.5 hour * 22 talks + 15.5 hour * 1.5 padding < 40 hour`
        - Decouple post-processing work from publishing work
        - hank: to handle post-processing
        - dc: handle publishing plan

So, we are talking ~40 hours, with the expectation that @dcwalk will take care of publishing planning (separate issue)

----

### Timeline

Begin: September 30
End: 

--- 

## Todos

- [x] @shrinks99 to review timeline and confirm deadline
- [x] @shrinks99 post-process
- [x] delivery

**Comment by Shrinks99** [comment]
Here's the link to view the tracking spreadsheet: https://docs.google.com/spreadsheets/d/1ovifZ1tLCy3m6fJGmabhOkpZ385ICk5EdrKDHcOD0Yw/edit?usp=sharing

I've finished all the templating stuff, will look at my schedule later today and fill out the due dates accordingly.  Also all the text in the intro (sans logo) uses the cool build-in typewriter effect that the conference title uses.  Neat!

**Comment by dcwalk** [comment]
Thanks for sharing your tracking sheet.

> I've finished all the templating stuff, will look at my schedule later today and fill out the due dates accordingly. Also all the text in the intro (sans logo) uses the cool build-in typewriter effect that the conference title uses. Neat!

I'm not sure what this means, I thought you and @garrying had locked down the splash/intro stuff, could you post if you are changing?

**Comment by Shrinks99** [comment]
The splash / intro is nearly identical, the talk title and name just build in the same way as the conference title does instead of fading in.  Will post a link in a few minutes

**Comment by Shrinks99** [comment]
Day 1 talks are all finished!  I plan to edit the rest of these on reading week which starts on the 14th but I'll be back at my workstation on the 16th (guaranteed) so that's when I plan to start the bulk of the work.  The spreadsheet has been updated with the dates.

Should I begin uploading what I have to YouTube?  Do we want to schedule when these start to release?  I'd really like to not upload these all in one go and release them once a day as to not spam everyone's YouTube feeds like The Linux Foundation just did because that's a bummer and nobody likes that :P
![Screenshot_2019-10-03_20-33-38](https://user-images.githubusercontent.com/5672810/66175393-79051500-e627-11e9-8151-99a5c56f9aeb.png)

**Comment by Shrinks99** [comment]
@dcwalk For Dr. Jennifer Wemigwans' talk would you like the territorial acknowledgement left in the video or would you like me to start the talk when she begins speaking?
Once I know this I would like to publish it to YouTube as an unlisted video so I can send it to her for approval so that it is approved (or not, we'll see what she says) in time for release.  She was the only presenter that wanted to review it first.

**Comment by dcwalk** [comment]
If you think it flows to leave the land acknowledgement/intro in I think that would be preferrable. 

Your plan sounds good, maybe you can propose your approach to her by email before publishing as unlisted and sharing? I'm not sure about the degree of concern/sensitivity here

**Comment by Shrinks99** [comment]
It works fine with it in, just wanted to make sure you were on-board with being included in the video since it's a little more than the usual introduction or ending bits.  It flows well!

I think Jennifer just wanted to review the video before we released it to make sure she didn't do a bad job speaking.  Unlisted videos can only be seen to those who have the link and we just won't share the link with anyone else (same thing as all my [intro previews](https://youtu.be/ujDbH52LVq8) which can't be seen on [my channel](https://www.youtube.com/channel/UCGLQ-5Liz8oO81kOdM0PMDw)).  If she likes it we will schedule the release to become public like all the other videos and if she doesn't it gets deleted off the channel.  I'll make sure this is noted in my email to her so it's clear that the YouTube link we're sending isn't publicly accessible.

That aside, all talks should be finished today!  I can start uploading them and setting up the descriptions and tags on YouTube as well if you'd like, they'll all be private until a release schedule is decided upon.

**Comment by dcwalk** [comment]
> Unlisted videos can only be seen to those who have the link and we just won't share the link with anyone else (same thing as all my intro previews which can't be seen on my channel).

Yes I understand that, my comment about waiting before uploading it is trying to be sensitive to the perception of checking in before moving forward.

**Comment by Shrinks99** [comment]
Would you like me to share the video with Jennifer using another method?  I can probably give her a Dropbox or Google Drive link if you think that's better than YouTube for this.

**Comment by dcwalk** [comment]
This could be a question you ask her. I don't have a preference.

**Comment by Shrinks99** [comment]
Editing is finished for all talks without blockers!  Jennifer's talk is finished editing and I've emailed her (and CCed the org email), the one talk with a blocker is Zach's (Zack's?) lightning talk because I don't definitively know how to spell his first name and unfortunately he didn't have his conference lanyard on during the talk.  Once I get some sort of answer there I can plop in the titles and render.

Other than that, thumbnails need to be generated and descriptions need to be put into text files and then we're done!  MUCH nicer process compared to last year and overall I'm quite happy :D

**Comment by benhylau** [comment]
I think @Shrinks99 has valid points about scheduled releases on YouTube. One the other hand, we are almost ready to make a big announcement to have everything ready on every platform, including our 600 Twitter + 300 mail subscribers, compared to our < 100 on YouTube. That said, scheduled releases could let YouTube better promote our content to attract more subscribers.

My preference is to release everything on IPFS, Internet Archive, and our partner ISOC, but schedule YouTube releases. In the newsletter announcement, tell people everything is on those platforms, and YouTube releases are scheduled over next couple weeks, and those releases have in their description link backs to our non-Google archives. This way we are fully utilizing YouTube's network effect, while giving a bias to the platforms we prefer.

**Comment by benhylau** [comment]
Next steps:
1. Get all post-processed assets from @Shrinks99
2. Prepare files for organizers to review and track review status on spreadsheet
3. Release to Infura IPFS, Internet Archive, and YouTube* by Nov 15
4. Hand-off to @garrying for website linking** and organizers to draft announcement email

*By Nov 15, we need YouTube links of all talks available on website [as in 2018](https://2018.ournetworks.ca/conference/recorded-talks/), but it seems we cannot keep them as _unlisted_ and then schedule for them to become _publicly listed_. If that's the case we'd have to release entire archive together on Nov 15. If there is a good way around this then we can schedule to release on YouTube one per day.

**@garry and I will also sort out how to link the livestream archive m3u8 such that bookmark links from before are preserved, and @darkdrgn2k and I probably need to move chunks to a more permanent place than our server

**Comment by Shrinks99** [comment]
> *By Nov 15, we need YouTube links of all talks available on website [as in 2018](https://2018.ournetworks.ca/conference/recorded-talks/), but it seems we cannot keep them as _unlisted_ and then schedule for them to become _publicly listed_. If that's the case we'd have to release entire archive together on Nov 15. If there is a good way around this then we can schedule to release on YouTube one per day.

Huh, so this works a little differently than I thought it would.  If you set the video to `Private` you can schedule an upload time but if it's just `Unlisted` you cannot.  If you manually set a video from `Unlisted` to `Public` it will go out to subscribers as a regular video upload would.

Alternatively, the YouTube links could just be put up on the website in one batch after they are all public if we don't want to manually make one video public every day which is a pretty dumb way of doing it but that would also work.

**Comment by benhylau** [comment]
I am definitely not going to manually unlist one video per day :D and we have set a hard deadline to get the 2019 site archived under the 2019.ournetworks.ca so it seems not worth it to do scheduled listing. We may as well publish the entire archive on Nov 15 so we have all the links for website.

Yes please give me access to spreadsheet!

**Comment by Shrinks99** [comment]
Videos have been uploaded to the Alexandria server with the same naming conventions as the 2018 videos.  Descriptions will be uploaded (taken from the website or created by me for the lightning talks) soon!

**Comment by benhylau** [comment]
Hank on chat:

>benhylau: you’ve been added to the sheet, pls use the same column with the colours in it and set to Approved once the video is good, if it’s not good fill with yellow and set it to Blocked with a reason why in the notes

Thanks @Shrinks99, I will follow the below checklist to review the archive, and add notes to a new column I created called _Reviewer Notes_ so I don't mix up your production notes. Here is the [spreadsheet link](https://docs.google.com/spreadsheets/d/1ovifZ1tLCy3m6fJGmabhOkpZ385ICk5EdrKDHcOD0Yw/edit?ts=5db98769#gid=0).

For each video:

- [ ] Verify the **filenames** have the correct spellings, consistent casings, and match between the 1080p, 720p, and descriptions folders
- [ ] Verify the **session name** in video and description are as listed on [program](https://ournetworks.ca/program/#sessions)
- [ ] Verify the **presenter names** in video and description are as listed on [program](https://ournetworks.ca/program/#sessions)
- [ ] Verify the **description** is in a text file consistent with the [2018 format](https://alexandria.tomesh.net/ournetworks/2018/descriptions/) and contains the text from [GitHub submissions](https://github.com/ournetworks/2019-submissions) unless it was revised on the website
- [ ] Verify the **video beginning and end** are correct
- [ ] Verify the **video and audio sync** at different points of the video

For the archive:

- [ ] Verify all videos we expect to publish are included
- [ ] Verify we are not including any video that should not be published

When all these verifications are completed, we'll be publishing the entire archive to:

- [ ] Alexandria, already there but need to IPFS pin (e.g. [2018](https://alexandria.tomesh.net/ournetworks/2018/))
- [ ] IPFS, on Infura.io (e.g. [2018](https://ipfs.infura.io/ipfs/QmQQfD1ztg1aG82VmUmutusbxn7tL4c2o1qHv1ivyWbNj6/))
- [ ] Internet Archive (e.g. [2018](https://archive.org/details/ournetworks2018))
- [ ] YouTube (e.g. [2018](https://www.youtube.com/playlist?list=PLx7_J32Ys60ey2bgSn2soAoBy0v9bBUbT))

**Comment by dcwalk** [comment]
@benhylau  -- we should work from the data file for sessions for all descriptions, presenter names, etc..., as it builds the recorded talks page. 

Can the txt files be updated to mirror what is here: https://github.com/ournetworks/ournetworks.ca/blob/master/_data/sessions.yml?

As you are the one doing that work I'm not sure what I'm supposed to verify. I've reviewed the production spreadsheet prior and confirmed that no talks were included that shouldn't be. It doesn't seem like I need to review again

**Comment by benhylau** [comment]
The two mostly match, but not 100% as they are intended to be pasted into YouTube descriptions, etc. with project links and context information. For example...

**Our_Networks_2019_Channel_Channel_by_Biyi_Wen.txt** contains 

>Video presentation by Biyi Wen, accompanying the exhibited artwork: Channel channel, a network for VPN access.

which I added.

**Our_Networks_2019_DHT_BFT_OMG_Know_Your_Building_Blocks_For_Decentralized_Applications_2019_Edition_by_Kirill_Pimenov.txt** contains

>It is going to be a revised and extended variant of my talk on Web3 Summit in Berlin in 2018: https://www.youtube.com/watch?v=J2lnjFqi-No

which is in the original GitHub submission. Other submissions have links that I extracted to put into the description, some giving important context such as in **Our_Networks_2019_Building_A_Modern_Memex_by_Andrew_Louis.txt**.

**Our_Networks_2019_The_Impotent_Medium_by_Farhad_Bahram.txt** has more information about the video, whereas in sessions.yml it just says

>Video presentation.

Then there are items like lightning talks, where it isn't a 1:1 mapping, as talks are broken up into individual video files, whereas on sessions.yml it is a single record.

@dcwalk is it important that they match 100%? I'd prefer descriptions in the archive to provide best context of the video on their own.

Matching sessions.yml means you'd like the _Keynote_ text to be included in the filenames and video title page right? cc. @Shrinks99 this probably means we need to re-render both keynotes and Channel Channel?

>title: "Keynote: Dr. Jennifer Wemigwans, A Digital Bundle Protecting and Promoting Indigenous Knowledge Online"
>title: "Keynote panel: May First, technology and revolution"

Regarding 6 and 7, I have checked that but want a second person to verify. If you feel the production spreadsheet is correct then we're fine, as I have verified that it matches the archive.

**Comment by dcwalk** [comment]
We didn't add the full descriptions to the youtube videos last year, only
the shortened ones that I believe matched the data file. E.g.:
https://www.youtube.com/watch?v=gDtO0qRAuTA  (I'd suggest we follow that
practice this year too. That would shorten many of the descriptions I
already see)

> Matching sessions.yml means you'd like the *Keynote* text to be included
in the filenames and video title page right?

No those don't have to be included, that is a workaround for the program.

Can you PR back in the changes that you see are improvements that you
mention in yours. I'm not saying the data file is perfect, Farhad's for
example was based on the late addition / lack of info we received,  but I
think the descriptions should be in sync.

**Comment by dcwalk** [comment]
> Then there are items like lightning talks, where it isn't a 1:1 mapping,
as talks are broken up into individual video files, whereas on sessions.yml
it is a single record.

We'll have to add these to the datafile to have the talks added to the
website

**Comment by Shrinks99** [comment]
I changed the keynote title name because it didn't follow the format used in the other videos.  I would propose that we follow the format used for everything else to keep things consistent.  For the panel I felt that it's important to signify that it's a panel in the title and I suppose the filename should be updated to match.  This is sort of subjective and up for debate though so I'll defer to what you want on both cases.  I would highly suggest that we don't put "Dr. Jennifer Wemigwans" in the video title however or else we'll be left with two instances of it in the title and that seems foolish.

**Comment by benhylau** [comment]
I have reviewed and approved all videos after @Shrinks99 re-published the incomplete files. I think we're good to go and have updated https://github.com/ournetworks/2019/issues/128#issuecomment-550218798 to reflect that 🎉 

@Shrinks99 can you start the upload to YouTube, using descriptions from [here](https://alexandria.tomesh.net/ournetworks/2019/descriptions/). I will wait for a final decision re: Jennifer's talk then publish to IPFS pin on Alexandria and Infura.io, and publish to IA.

**Comment by benhylau** [comment]
Fixed mismatched filenames and confirmed they now match across directories. Useful commands for the verification:

```
# ls descriptions | sed 's/.txt//g' | sha1sum
32cbf94c27da6c77986475c35994fd3097a281bd  -
# ls 720p | sed 's/_720p.mp4//g' | sha1sum
32cbf94c27da6c77986475c35994fd3097a281bd  -
# ls 1080p | sed 's/_1080p.mp4//g' | sha1sum
32cbf94c27da6c77986475c35994fd3097a281bd  -
```

Changed file owner and permissions to be same as 2018 on alexandria.

The archive to be published has the following sha1sum:

```
# find ./descriptions -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum
ef3ccb9bf4825c3a921336b974dac8df5bb5c9ff  -
# find ./720p -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum
a5d7e17b4b3dd5e70105a36a5734c3b2ecd5ca2b  -
# find ./1080p -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum
e5db760fbcd19b05a887fb17774106addc8c1b94  -
```

@Shrinks99 can you confirm these are the same on your local? This is excluding Jennifer's talk in all folders.

**Comment by Shrinks99** [comment]
I will be able to confirm these changes and start uploading on November 23rd.

**Comment by Shrinks99** [comment]
All of the talks have been uploaded to YouTube!  They are currently all up as unlisted on our channel.

YouTube has changed their system and it seems that we can now schedule videos to publish while they remain unlisted, this would allow us to release one video per day on YouTube while keeping the video URLs which can be accessed through the website or the conference playlist.

I'll get on thumbnails ASAP and hopefully we can push this thing out the door soon!

**Comment by benhylau** [comment]
Used following command in `screen` to pin 2019 archive on Alexandria. Note `--local` deprecation shouldn't affect results:

```
benhylau@alexandria:~$ sudo su ipfs
ipfs@alexandria:/home/benhylau$ cd /mnt/sda1/data/ournetworks/2019
ipfs@alexandria:~/data/ournetworks/2019$ ipfs add --local=true --nocopy --fscache -r --progress .
09:22:26.939 ERROR core/comma: Command 'add', --local is deprecated, use --offline instead env.go:40
```

**Comment by benhylau** [comment]
# Internet Archive upload

Archive description:

```
Recorded talks from State of Our Networks 2019: RE: Infrastructures, held September 20–22, 2019 in Toronto, ON:

- A digital bundle protecting and promoting indigenous knowledge online by Dr. Jennifer Wemigwans
- A technical introduction to IPFS by Hector Sanjuan
- Building a modern Memex by Andrew Louis
- Channel Channel by Biyi Wen
- Collective resistance to state controls on information by Cecylia Bocovich
- Cryptoeconomics: Towards mass behavioral engineering or a network commons by Jaya Klara Brekke / Dan Hassan
- DHT, BFT, OMG: Know your building blocks for decentralized applications (2019 edition) by Kirill Pimenov
- Distributed internet archiving! + Low-power long-distance meshing with LoRaWAN by Nick Sweeting
- Distributed secure routing in permissionless flat networks by Benedict Lau
- Distributing knowledge of digital workflows via workshops and support groups by Zack
- Hugo, WASM plus IPFS blogging by Jim Pick
- May First, technology and revolution by Alfredo Lopez / Ellie Ade Kur / Lorraine Chuen / Victoria Barnett
- Mesh lightning talks: Freifunk by Felix Kaechele
- Mesh lightning talks: I2P intro for app devs by idk
- Mesh lightning talks: NYC Mesh by Jillian Murphy / Scott Rasmussen
- Mesh lightning talks: Sarantaporo.gr by Vassilis Chryssos
- Networks as sculpture by Lai Yi Ohlsen
- Regulationism and the need for a digital postmodernism by Corey Abell
- Remaking the web: Competing visions of decentralization by Jack Jamieson
- Social, artistic, and theoretical experiments with decentralized festivals by Andreas Dzialocha
- Solar powered website by Marie Otsuka / Lauren Traugott-Campbell
- Spectacular grammar: Infrastructure as a Universal language by Renée Reizman
- The impotent medium by Farhad Bahram
- The Netifesto by Ryan Kelln

https://ournetworks.ca/
```

URL: https://archive.org/details/ournetworks2019

**Comment by benhylau** [comment]
# IPFS pinning livestream archive

I assume live.mesh.world already has all the livestream chunks on the m3u8 files in [ournetworks/ournetworks.ca/pull/154/](http://github.com/ournetworks/ournetworks.ca/pull/154/) pinned to its IPFS node. So I generated a list of the hashes using:

```
$ grep 'ipfs/' live-*.m3u8 | sed 's|.*ipfs/||g' > ipfs-cids.txt
```

There are 1449 of them. Then in a `screen`, I `cat` the file and run Infura's pinning API on each hash (takes > a day to iterate through) using:

```
$ cat ipfs-cids.txt | xargs -I {} curl "https://ipfs.infura.io:5001/api/v0/pin/add?arg=/ipfs/{}&recursive=true&progress=true" >> ipfs-cids.log
```

The log file gets mostly `{"Pins":null}` with occasional successful pins like:

```
...
{"Pins":null,"Progress":77}
{"Pins":["QmUCqFERhFg5EEuTvzBnowVYKEvKuxgsBS4qLpiifcP1jn"]}
```

So I assume the `{"Pins":null}` means the Infura node is unable to resolve the hash. Subsequent calls occasionally makes it pin successfully, but more often it still returns `{"Pins":null}` after many attempts.

**Comment by dcwalk** [comment]
This was done and the videos are added! Closing this :)
