### ISSUE TITLE
Zine library planning

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2019#73]
_Edit: reforming this issue to track todos for Zine Library_ 

## Description

- We set up a cozy lending library of paper zines, as well as a computer terminal for digital/dat zines, with sofa, plants, bookshelves from a mix of onsite and offsite stuff
- It will be located in the "[Gathering Space](https://www.datocms-assets.com/5128/1551313423-tmac-event-space-floorplan-january-2019.pdf)," right off the stairs/elevator as you enter TMAC
- Registration will be set up nearby (line of site), we anticipate some "staffed" hours but will not require someone attend to it the entire conference (volunteers at registration will also assist with zine lib.?)
- The space will be free/open to the public throughout
- Workshops will be scheduled there on the Sat/Sun (maybe we want a zine-making sesh as an event?)
- We will have a "checkout" ability using the TMAC photocopier + risograph
- There will be space for 1-3 vendors, but the format is not a fair, we can decide whether to proceed with a call
- We will do a call for tech zines, as well as research and curate those we know about for inclusion
    - There is a modest budget for purchasing zines
    - Folks who submit can indicate whether they want to have their zine "checkoutable" and we'll do the honour system / red-dotting to indicate
- We will speak with toronto zine library about donating the collection (and any zines made at the event?)

Notes:
- https://github.com/ournetworks/2019/issues/52
- https://github.com/ournetworks/2019/issues/34
- https://github.com/ournetworks/2019/blob/master/notes/2019-07-16-planning-call-onesandzeros.md

## TODOs:

- [x] develop initial plan/pitch for zine library
- [x] confirm whether a collaboration (seems like we're doing this solo!)
- [x] call for zines up 
- [x] build equipment list (and where stuff is coming from)
- [x] curate/build catalogue of zines, initial research here #52
- [x] design for final version of website?

--- 

Had a great chat with uniphil about zine library possibilities. Next step is to develop a concise description of our plans and firm up whether a collaboration makes sense.

**Comment by dcwalk** [comment]
Here is the text on that plan:

Short description:

- We set up a cozy lending library of paper zines, as well as a computer terminal for digital/dat zines, with sofa, plants, bookshelves from a mix of onsite and offsite stuff
- It will be located in the "[Gathering Space](https://www.datocms-assets.com/5128/1551313423-tmac-event-space-floorplan-january-2019.pdf)," right off the stairs/elevator as you enter TMAC
- Registration will be set up nearby (line of site), we anticipate some "staffed" hours but will not require someone attend to it the entire conference (volunteers at registration will also assist with zine lib.?)
- The space will be free/open to the public throughout
- Workshops will be scheduled there on the Sat/Sun (maybe we want a zine-making sesh as an event?)
- We will have a "checkout" ability using the TMAC photocopier + risograph
- There will be space for 1-3 vendors, but the format is not a fair, we can decide whether to proceed with a call
- We will do a call for tech zines, as well as research and curate those we know about for inclusion
    - There is a modest budget for purchasing zines
    - Folks who submit can indicate whether they want to have their zine "checkoutable" and we'll do the honour system / red-dotting to indicate
- We will speak with toronto zine library about donating the collection (and any zines made at the event?)

Notes:
- https://github.com/ournetworks/2019/issues/52
- https://github.com/ournetworks/2019/issues/34
- https://github.com/ournetworks/2019/blob/master/notes/2019-07-16-planning-call-onesandzeros.md

**Comment by dcwalk** [comment]
We planned and had the zine library, I'm gonna close this and we can re-ticket for any post event website designs we'd like to do
